### ISSUE TITLE
Fix changelog format with github PR

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/gh-jira-changelog#4]
Currently the changelog format doesn't consider github PR authors and PR numbers. It's good to indicate the PR author or jira assignee on the Changelog item atleast. This allows us to create changelog accurately.

### Tasks
- [ ] Attach PR authors on the changelog entry
- [x] fix changelog url
- [x] auto populator `repo_url` flag if not provided based on git remote origin url
- [ ] make `target_committish` configurable for PR based changelog generation.
